### ISSUE TITLE
Drop the redundant `r` from the definition of `Parser`

### ISSUE THREAD

**Issue by nikita-volkov** [Gabriel439/Haskell-Pipes-Parse-Library#33]
Currently it's impossible to use `Parser` in a monad-transformer stack. In cases like the following:

```haskell
type MyParser s b m a = StateT s (Pipes.Parse.Parser b m) a
```

the compiler complains with:

```
Type synonym ‘Pipes.Parse.Parser’ should have 3 arguments, but has been given 2
```

So I suggest to remove the redundant `r` from the definition of `Parser`:

```diff
- type Parser a m r = forall x . StateT (Producer a m x) m r
+ type Parser a m = forall x . StateT (Producer a m x) m
```

Of course, it's possible to work around the issue by expanding the type synonym in place, but it's still an issue.

**Comment by Gabriel439** [comment]
This doesn't work (the library won't compile if you delete the `r` on both sides), because now you're universally quantifying a higher-kinded type, which is almost always not going to behave well.

The reason this causes problems is that if you write:

```haskell
Parser a m r
```

... the compiler will expand  it to:

```haskell
(forall x . StateT (Producer a m x) m) r
```

... which is not the same thing as:

```haskell
forall x . StateT (Producer a m x) m r
```

**Comment by nikita-volkov** [comment]
Sorry. My bad.

**Comment by Gabriel439** [comment]
No problem at all! :)
