### ISSUE TITLE
`zoom` links in Pipes.Parse.Tutorial are broken

### ISSUE THREAD

**Issue by tswilkinson** [Gabriel439/Haskell-Pipes-Parse-Library#38]

**Comment by Gabriel439** [comment]
This is because I had to manually upload the documentation which sometimes results in links like that.  The best I can do is delete the documentaton and hope that Hackage successfully rebuilds the documentation by tomorrow evening.  If not, then I will have to redo the manual upload.

**Comment by Gabriel439** [comment]
Okay, so it looks like this was not an issue with manual upload of the documentation.  Hackage did successfully rebuild the docs on its own after I deleted the documentation, but the broken link still persisted.

Looking through previous package versions it looks like this never worked before but I never realized it before you reported it.  `pipes-parse` does not explicitly depend on `lens-family-core` which provides that specific `zoom`, so even with a fully qualified name the `haddock` tool just generates a dead link.  I don't think the link can be fixed short of depending on `lens-family-core`, which I don't want to in order to be as `lens`-library-agnostic as possible.

However, what I can do is remove the link entirely so that users aren't confused.  Does that sound like an acceptable solution for you?

**Comment by tswilkinson** [comment]
That sounds fine!  I don't mind very much about the link, I just thought you should know about it.
